.\" This man page is inspired in hithrere.1 from GNU hithere 1.0.
.TH FREEDOMBOXCOUNTDOWN "1" "January 2021" "freedomboxcountdown 1.0" "User Commands"
.SH NAME
freedomboxcountdown - greet user
.SH SYNOPSIS
.B freedomboxcountdown
.SH DESCRIPTION
greets the user, or the world.
.SH AUTHORS
Original work by duchonic, 202x.
.br
engineered to test debian pakage and fredombox stuff
